// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDettqBR-i1oz_Kzd0o9_R2iGZMhUPREHU',
    appId: '1:86047355226:web:2d45f4a7ef1f3b579f0363',
    messagingSenderId: '86047355226',
    projectId: 'uasppb-46f11',
    authDomain: 'uasppb-46f11.firebaseapp.com',
    storageBucket: 'uasppb-46f11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1AChzvOq5a264lMLgP4iUH7mHQwfdeU',
    appId: '1:86047355226:android:3ced91a634cb26e39f0363',
    messagingSenderId: '86047355226',
    projectId: 'uasppb-46f11',
    storageBucket: 'uasppb-46f11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZfgEHda0ljlMdT3qPMC9V9wpGfbCC1M',
    appId: '1:86047355226:ios:48b939fc28ebb4ce9f0363',
    messagingSenderId: '86047355226',
    projectId: 'uasppb-46f11',
    storageBucket: 'uasppb-46f11.appspot.com',
    iosBundleId: 'com.example.uasppb2021130024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ZfgEHda0ljlMdT3qPMC9V9wpGfbCC1M',
    appId: '1:86047355226:ios:48b939fc28ebb4ce9f0363',
    messagingSenderId: '86047355226',
    projectId: 'uasppb-46f11',
    storageBucket: 'uasppb-46f11.appspot.com',
    iosBundleId: 'com.example.uasppb2021130024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDettqBR-i1oz_Kzd0o9_R2iGZMhUPREHU',
    appId: '1:86047355226:web:aa177afb28af9c079f0363',
    messagingSenderId: '86047355226',
    projectId: 'uasppb-46f11',
    authDomain: 'uasppb-46f11.firebaseapp.com',
    storageBucket: 'uasppb-46f11.appspot.com',
  );

}